version: "3.1"

services:
  web:
    image: httpd:2.4-alpine
    volumes:
      - ./:/usr/local/apache2/htdocs
      - ./docker/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
    ports:
      - 8000:80
