version: '3.1'

services:
  web:
    image: code-sandbox
    volumes:
      - ./:/usr/local/apache2/htdocs
      - ./docker/web/httpd.conf:/usr/local/apache2/conf/httpd.conf
    build:
      context: ./docker/web/
    ports:
      - 8000:80

  test:
    image: code-sandbox-test
    volumes:
      - ./:/src/
    build:
      context: ./docker/test/
    depends_on:
      - web
    links:
      - web
    # https://stackoverflow.com/a/53975412/3145856
    # https://github.com/docker/compose/issues/5574
    security_opt:
      - seccomp:"./docker/test/chrome.json"
